name: Build Tweak
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          brew install dpkg ldid
      - name: Build Tweak
        run: |
          git clone --recursive https://github.com/theos/theos
          export THEOS=$GITHUB_WORKSPACE/theos
          mkdir -p packages
          make package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tweak-package
          path: packages/*.deb
